# Docker Compose override for development environment
version: '3.8'

services:
  easyauth-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=false
      - EasyAuth__Framework__EnableSwagger=true
      - EasyAuth__Framework__EnableDetailedErrors=true
    volumes:
      - ./src:/src:ro
      - ./logs:/app/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.easyauth.rule=Host(`easyauth.localhost`)"

  sqlserver:
    environment:
      - MSSQL_AGENT_ENABLED=true
    volumes:
      - ./sql-scripts/dev:/docker-entrypoint-initdb.d
    ports:
      - "1433:1433"

  # Development database GUI
  sqlserver-gui:
    image: dbeaver/cloudbeaver:latest
    profiles:
      - dev
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    networks:
      - easyauth-network
    restart: unless-stopped
    depends_on:
      - sqlserver

volumes:
  cloudbeaver_data: