name: 🔒 Scheduled Security Scan

on:
  schedule:
    # Run security scan daily at 3 AM UTC (low traffic time)
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Type of security scan'
        required: true
        default: 'full'
        type: choice
        options: ['full', 'dependencies-only', 'code-only']

env:
  DOTNET_VERSION_8: '8.0.x'

jobs:
  security-scan:
    name: Security Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      if: github.event.inputs.scan_type != 'dependencies-only'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION_8 }}

    # Dependency vulnerability scanning
    - name: Run Dependency Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'dependency-results.sarif'
        severity: 'CRITICAL,HIGH,MEDIUM'

    # Code security scanning
    - name: Initialize CodeQL
      if: github.event.inputs.scan_type != 'dependencies-only'
      uses: github/codeql-action/init@v3
      with:
        languages: 'csharp,javascript'
        config-file: ./.github/codeql-config.yml

    - name: Build for CodeQL Analysis
      if: github.event.inputs.scan_type != 'dependencies-only'
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore \
          -p:TreatWarningsAsErrors=false

    - name: Perform CodeQL Analysis
      if: github.event.inputs.scan_type != 'dependencies-only'
      uses: github/codeql-action/analyze@v3

    # Upload all security results
    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'dependency-results.sarif'

    # Create security report issue if critical vulnerabilities found
    - name: Create Security Issue on Critical Findings
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const title = `🚨 Critical Security Vulnerabilities Found - ${new Date().toISOString().split('T')[0]}`;
          const body = `
          ## Critical Security Vulnerabilities Detected
          
          The scheduled security scan has detected critical vulnerabilities that require immediate attention.
          
          **Scan Date:** ${new Date().toISOString()}
          **Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          
          ### Next Steps:
          1. Review the security findings in the Security tab
          2. Update dependencies with known vulnerabilities
          3. Address any code security issues identified
          4. Re-run the security scan to verify fixes
          
          ### Auto-generated by EasyAuth Security Workflow
          `;
          
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: ['security', 'critical', 'automated']
          });

    - name: Summary
      if: always()
      run: |
        echo "## 🔒 Security Scan Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Scan Type:** ${{ github.event.inputs.scan_type || 'full' }}" >> $GITHUB_STEP_SUMMARY
        echo "**Scan Date:** $(date -u)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Results" >> $GITHUB_STEP_SUMMARY
        echo "- Dependency vulnerabilities: Check Security tab for details" >> $GITHUB_STEP_SUMMARY
        echo "- Code security analysis: Check CodeQL results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Links" >> $GITHUB_STEP_SUMMARY
        echo "- [Security Advisories](/${{ github.repository }}/security/advisories)" >> $GITHUB_STEP_SUMMARY
        echo "- [Dependabot Alerts](/${{ github.repository }}/security/dependabot)" >> $GITHUB_STEP_SUMMARY